apiVersion: v1
kind: Pod
metadata:
  name: app-video
spec:
  schedulerName: my-scheduler
  nodeName: node1
  containers:
  - name: app-video
    image: jolyonjian/apps:cpu-1.0
    command: ["/tmp/workdir/run.sh"]
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
  restartPolicy: OnFailure
