apiVersion: v1
kind: Pod
metadata:
  name: app-net
spec:
  schedulerName: my-scheduler
  nodeName: node1
  containers:
  - name: app-net
    image: jolyonjian/apps:net-1.0
    command: ["/workspace/run.sh"]
    resources:
      limits:
        cpu: "500m"
      requests:
        cpu: "500m"
  restartPolicy: OnFailure
